# Generated by Django 4.0.4 on 2022-08-13 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=200)),
                ('act_type', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/act_images')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/act_files')),
                ('completed', models.BooleanField(default=False)),
                ('act_processing', models.CharField(choices=[('Ожидание принятия заявки', 'Waiting'), ('Заявки принята', 'Accepted'), ('Заявка возвращена', 'Returned')], default='Ожидание принятия заявки', max_length=25)),
                ('do_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
