# Generated by Django 4.0.4 on 2022-10-23 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='act',
            options={'ordering': ['date_updated']},
        ),
    ]
