# Generated by Django 4.0.4 on 2023-02-14 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acts', '0002_alter_act_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='executer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acts_executer', to=settings.AUTH_USER_MODEL),
        ),
    ]
